db:
  db_name: c9
  host: localhost
  password: ''
  username: nelsonk
  
# For every table in the database, add an item here
models:
  DB:
    - Driver
    - Form
    - Offer
    - OfferPassenger
    - Request
    - Rider
    - User
    

